#!/usr/bin/env bash

set -e
DIR=$(cd `dirname $0` && pwd)
SDK_NAME="Node"
SDK_RUN="node-run"

. "${DIR}/bin/base-run"

REQUESTER_FILE=""
CMD="npm run start"

if [[ $DEV_MODE -eq 1 ]]; then
    REQUESTER_FILE="-v ${DIR}/data_node/requester.ts:/app/requester.ts"
    CMD="npm run dev"
fi

if [[ ! -z "${JSON_FILE}" ]]; then
    docker container run -it --rm \
        -e AUTH_TYPE="${AUTH_TYPE}" \
        -e AUTH_KEY="${AUTH_KEY}" \
        -e SERVER="${SERVER}" \
        -e DEV_MODE="${DEV_MODE}" \
        -v "${JSON_FILE}":"/app/data.json" \
        -v "${DIR}/file_uploads":"/file_uploads" \
        ${REQUESTER_FILE} \
        docker.io/jtreminio/hellosign-node-sdk \
        ${CMD}
fi

if [[ ! -z "${JSON_STRING}" ]]; then
    docker container run -it --rm \
        -e AUTH_TYPE="${AUTH_TYPE}" \
        -e AUTH_KEY="${AUTH_KEY}" \
        -e SERVER="${SERVER}" \
        -e JSON_STRING="${JSON_STRING}" \
        -e DEV_MODE="${DEV_MODE}" \
        -v "${DIR}/file_uploads":"/file_uploads" \
        ${REQUESTER_FILE} \
        docker.io/jtreminio/hellosign-node-sdk \
        ${CMD}
fi
