#!/usr/bin/env bash

set -e

docker image build \
  --no-cache \
  -t jtreminio/hellosign-php-sdk:latest \
  -f data-php/Dockerfile \
  ./data-php

docker container run -it --rm \
  docker.io/jtreminio/hellosign-php-sdk \
    ./vendor/bin/phpunit
