#!/usr/bin/env bash

set -e
DIR=$(cd `dirname $0` && pwd)
SDK_NAME="PHP"
SDK_RUN="php-run"

. "${DIR}/bin/base-run"

if [[ ! -z "${JSON_FILE}" ]]; then
    docker container run -it --rm \
        -e AUTH_TYPE="${AUTH_TYPE}" \
        -e AUTH_KEY="${AUTH_KEY}" \
        -e SERVER="${SERVER}" \
        -v "${JSON_FILE}":"/data.json" \
        -v "${DIR}/test_assets":"/file_uploads" \
        -v "${DIR}/data_php/requester.php":"/requester.php" \
        -v "${DIR}/data_php/ApiRequester":"/ApiRequester" \
        docker.io/jtreminio/hellosign-php-sdk \
        php /requester.php
fi

if [[ ! -z "${JSON_STRING}" ]]; then
    docker container run -it --rm \
        -e AUTH_TYPE="${AUTH_TYPE}" \
        -e AUTH_KEY="${AUTH_KEY}" \
        -e SERVER="${SERVER}" \
        -e JSON_STRING="${JSON_STRING}" \
        -v "${DIR}/test_assets":"/file_uploads" \
        -v "${DIR}/data_php/requester.php":"/requester.php" \
        -v "${DIR}/data_php/ApiRequester":"/ApiRequester" \
        docker.io/jtreminio/hellosign-php-sdk \
        php /requester.php
fi
