#!/usr/bin/env bash

set -e
DIR=$(cd `dirname $0` && pwd)
SDK_NAME="PHP"
SDK_RUN="php-run"

. "${DIR}/bin/base-run"

REQUESTER_FILE=""

if [[ $DEV_MODE -eq 1 ]]; then
    REQUESTER_FILE="-v ${DIR}/data_ruby/requester.rb:/app/requester.rb"
fi

if [[ ! -z "${JSON_FILE}" ]]; then
    JSON_STRING=$(cat "${JSON_FILE}" | base64)
fi

docker container run --rm \
    -e AUTH_TYPE="${AUTH_TYPE}" \
    -e AUTH_KEY="${AUTH_KEY}" \
    -e SERVER="${SERVER}" \
    -e JSON_STRING="${JSON_STRING}" \
    -e DEV_MODE="${DEV_MODE}" \
    -v ${UPLOADS_DIR}:"/file_uploads" \
    ${REQUESTER_FILE} \
    docker.io/jtreminio/hellosign-ruby-sdk \
    bundle exec ruby /app/requester.rb
